Machine learning tutorial from the udemy

In [110]:
import numpy as np #work with arrays and math things
import pandas as pd # working on dataset 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

##**Loading the dataset**

In [111]:
data = pd.read_csv('Data.csv')
data.head(10)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

##**Data Preprocessing**

In [112]:
#feature and Dependent variable 
#features are the independent variable and labels are the dependent variable 
x = data.iloc[:,:-1] #spliting the dataset # -1 is the index of last column 
#it include the lower bound and exclude the upper bound 
y = data.iloc[:,-1].values # : is the range  in python

In [113]:
print(x)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [114]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [115]:
x.iloc[:,1:3]

    Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

###**Taking care of missing data**

In [116]:
##replace the missing data(average , median and the most frequent can be used )
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy="mean") # replace the Nan-values to mean 
# x = imputer.fit(x[:,1:3])
x.iloc[:,1:3] = imputer.fit_transform(x.iloc[:,1:3])
x = x.values

In [117]:
type(x)

numpy.ndarray

##**Econding Categorical data**

In [118]:
#chaning the String data in to the numerical data 
#Encodinga categorical data  
#onehot encoding - binary vector for each of the country 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#mix these two class to transform our data 

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])] ,remainder='passthrough' ) 
# X = np.array(ct.fit_transform(x[0]))
x = ct.fit_transform(x) #x is already a numpy array so , np.array() is not required

In [119]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [120]:
#when two classes label Encoding , if more classes do onehot Encoding 
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y= le.fit_transform(y)

In [121]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

##**Training testing and spliting**

In [152]:
from sklearn.model_selection import train_test_split 

x_train, x_test ,y_train ,y_test = train_test_split(x, y, test_size=0.2 ,random_state= 1)
#if random state is zero we can get same test and train data

In [153]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [154]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

##Feature Scaling 
 **Normalidation**


 **Standardrisation**

In [ ]:
#when standarisation and when Normalisation??
#standaridition all the time and normalisation is recommended when we have normal distribution in all of the features

##**Standardization**

In [155]:
#feature scaling is applied on only on the training set 
#don't apply the feature scaling on the dummy variable , that is the encoded variable 
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler()

# Fit and transform the training data
x_train[:,3:] = sc.fit_transform(x_train[:,3:])

# Transform the test data using the same scaler object
x_test[:,3:] = sc.transform(x_test[:,3:])

#fit provides all the necessary information and transform will apply the trnsform on the dataset

In [156]:
x_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

In [158]:
x_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)